### ISSUE TITLE
Avoid private API's in broccoli nodes

### ISSUE THREAD

**Issue by rwjblue** [SparshithNR/fs-merger#13]
https://github.com/SparshithNR/fs-merger/blob/021b9075fe08d28edb99c550bdae6b41080e3fa4/index.js#L20-L23

**Comment by SparshithNR** [comment]
I couldn't find a public API in the broccoli node to identify type of the node. 
```
_annotation: undefined
_directoryPath: "/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/@ember/test-helpers/addon-test-support"
_instantiationStack: "    at WatchedDir.Directory (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/broccoli-source/index.js:14:31)↵    at new WatchedDir (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/broccoli-source/index.js:58:13)↵    at Class.treeGenerator (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/models/addon.js:573:14)↵    at Class._treeFor (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/models/addon.js:680:19)↵    at Class.treeFor (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/models/addon.js:644:21)↵    at /Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/models/addon.js:518:26↵    at Array.reduce (<anonymous>)↵    at Class.eachAddonInvoke (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/models/addon.js:515:24)↵    at Class.treeFor (/Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/models/addon.js:643:22)↵    at /Users/snrai/gitHub/ember-cli-htmlbars/node_modules/ember-cli/lib/broccoli/ember-app.js:704:26"
_name: "WatchedDir"
_watched: true
__proto__: Directory
```
WatchedDir doesn't have an outputPath, they have `_directoryPath`. There is no public way to access it.

**Comment by rwjblue** [comment]
```js
const getNodeInfo = require('broccoli-get-info');

// ...snip...
let nodeInfo = getNodeInfo(tree);

if (nodeInfo.nodeType === 'source' && nodeInfo.watched) {

}
```
