### ISSUE TITLE
Accessing `at` using `FSMerger.fs` proxy causes error.

### ISSUE THREAD

**Issue by SparshithNR** [SparshithNR/fs-merger#27]
```js
let fsMerger = new FSMerger([`a`,`b`]);
let fileAt = fsMerger.fs.at(1).readFileSync('test.txt'); //errors
```
```sh
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number
      at validateString (internal/validators.js:112:11)
      at Object.isAbsolute (path.js:1030:5)
      at FSMerger.handleOperation (node_modules/fs-merger/dist/index.js:51:15)
```

**Comment by stefanpenner** [comment]
is this fixed by #28 ?
