### ISSUE TITLE
`FSMerger.prototype.entries()` should likely not error

### ISSUE THREAD

**Issue by stefanpenner** [SparshithNR/fs-merger#31]
Running: `this.input.entries()`  currently throws with:

```
> this.input.entries()
NodeError: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.isAbsolute (path.js:1136:5)
    at FSMerger.handleOperation (/Users/spenner/src/stefanpenner/gql-experiment/node_modules/fs-merger/dist/index.js:54:39)
    at eval (eval at build (/Users/spenner/src/stefanpenner/gql-experiment/index.js:7:5), <anonymous>:1:12)
    at GQL.build (/Users/spenner/src/stefanpenner/gql-experiment/index.js:7:5)
    at TransformNodeWrapper.build (/Users/spenner/src/stefanpenner/gql-experiment/node_modules/broccoli/dist/wrappers/transform-node.js:70:39)
    at pipeline.then (/Users/spenner/src/stefanpenner/gql-experiment/node_modules/broccoli/dist/builder.js:118:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This isn't super helpful, it should likely rather just assume the caller wants all relevant entries.

`this.input.entries()` should likely perform like `this.input.entries('.')`
```

sh

**Comment by SparshithNR** [comment]
I will have a look. :slightly_smiling_face: I remember this case.. I am not sure why I made this decision of expecting to have at least one argument. If there is no exact reason, I will make this change.
